# Generated by Django 4.0.5 on 2024-01-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tamanho',
            field=models.TextField(default='', max_length=20),
        ),
    ]
